name: Admin Deploy (Infra + App)

on:
  push:
    branches: [ develop, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # Define variáveis com base na branch
      ENV_NAME: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}
      AWS_REGION: "us-east-1"

    steps:
      - uses: actions/checkout@v4

      # 1. Setup Terraform
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init & Apply
        working-directory: infra/stacks/admin_stack
        run: |
          # Inicializa usando uma chave de estado diferente para cada ambiente
          terraform init -backend-config="key=tf-state/admin-${{ env.ENV_NAME }}.tfstate"
          
          # Aplica a infra usando o arquivo de variáveis correto
          # (Certifique-se de que os arquivos dev.tfvars e prod.tfvars existam em infra/envs/)
          terraform apply -var-file=../../envs/${{ env.ENV_NAME }}.tfvars -auto-approve