name: Deploy Infra

on:
  push:
    branches:
      - develop
      - master
    paths:
      - 'infra/**'

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    
    # Definindo permissões básicas para o token do GitHub
    permissions:
      contents: read
      pull-requests: write

    env:
      ENV: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.3" # Versão que está no seu tfstate

      - name: Terraform Init
        id: init
        working-directory: infra/stacks/admin_stack
        run: |
          terraform init \
            -backend-config="key=tf-state/admin-${{ env.ENV }}.tfstate" \
            -reconfigure

      - name: Terraform Apply
        id: apply
        working-directory: infra/stacks/admin_stack
        run: |
          terraform apply \
            -var-file=../../envs/${{ env.ENV }}.tfvars \
            -auto-approve