name: Deploy Infra

on:
  push:
    branches: [ develop, master ]
    paths:
      - 'infra/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ENV: ${{ github.ref == 'refs/heads/master' && 'prod' || 'dev' }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra/stacks/admin_stack
        run: |
          # Usamos uma chave de estado diferente para cada ambiente para não sobrescrever
          terraform init -backend-config="key=tf-state/admin-${{ env.ENV }}.tfstate"

      - name: Terraform Apply
        working-directory: infra/stacks/admin_stack
        run: |
          # Aplica usando o arquivo de variáveis do ambiente correto
          terraform apply -var-file=../../envs/${{ env.ENV }}.tfvars -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"