name: Deploy Frontend Admin

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'frontend/admin/**'
      - '.github/workflows/deploy-front.yml'
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    env:
      # Lógica de ambiente
      ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
      # Nome do bucket seguindo o padrão que criamos no Terraform
      BUCKET_NAME: "drop-shop-${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}-admin-frontend"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/admin/package-lock.json

      - name: Install & Build
        working-directory: frontend/admin
        run: |
          npm install
          # Se for main, usa 'production'. Se for develop, usa 'staging'.
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            npm run build -- --mode production
          else
            npm run build -- --mode staging
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        working-directory: frontend/admin
        run: |
          aws s3 sync dist/ s3://${{ env.BUCKET_NAME }} --delete

      - name: Invalidate CloudFront
        run: |
          # Aqui buscamos o ID da secret que você deve configurar (CF_ID_DEV e CF_ID_PROD)
          DIST_ID=${{ env.ENV == 'prod' && secrets.CF_ID_PROD || secrets.CF_ID_DEV }}
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/index.html"